[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "xlang"
version = "0.0.1"
dependencies = [
    "click",
]

[project.scripts]
xcc = "xlang.xcc:xcc"
xlang = "xlang.xlang:xlang"